### ISSUE TITLE
Do we need to specify the schema while trying to Aquire tables 

### ISSUE THREAD

**Issue by bheemreddy181** [khaiql/dbcleaner#14]
I started seeing below error all of a sudden when I added schema_name in front of the table it was working fine.

```
- FAIL: TestFunctionalTestSuite/TestSendNOAA (100.04s)
        suite.go:62: test panicked: failed to ACQUIRE tables [notice] after 5 times
            goroutine 10 [running]:
            runtime/debug.Stack(0xc0006e1c78, 0x48ced20, 0xc0006321f0)
                /usr/local/go1.12.7.darwin-amd64/src/runtime/debug/stack.go:24 +0x9d
            github.com/stretchr/testify/suite.failOnPanic(0xc00020c000)
                /Users/bvennapureddy/go/pkg/mod/github.com/stretchr/testify@v1.4.0/suite/suite.go:62 +0x57
            panic(0x48ced20, 0xc0006321f0)
                /usr/local/go1.12.7.darwin-amd64/src/runtime/panic.go:522 +0x1b5
            gopkg.in/khaiql/dbcleaner%2ev2.(*cleanerImpl).Acquire(0xc000033700, 0xc00022a0c0, 0x4, 0x4)
                /Users/bvennapureddy/go/pkg/mod/gopkg.in/khaiql/dbcleaner.v2@v2.3.0/dbcleaner.go:160 +0x586
            git.enova.com/services/customer_notices.(*FunctionalTestSuite).SetupTest(0xc000258f20)
                /Users/bvennapureddy/customer_notices/init_test.go:123 +0x126
            github.com/stretchr/testify/suite.Run.func2(0xc00020c000)
                /Users/bvennapureddy/go/pkg/mod/github.com/stretchr/testify@v1.4.0/suite/suite.go:119 +0x3e7
            testing.tRunner(0xc00020c000, 0xc000191980)
                /usr/local/go1.12.7.darwin-amd64/src/testing/testing.go:865 +0xc0
            created by testing.(*T).Run
                /usr/local/go1.12.7.darwin-amd64/src/testing/testing.go:916 +0x35a
```

**Comment by khaiql** [comment]
This message means that you have a deadlock and it couldn't acquire the table, after excessive retries. I don't know your code so couldn't comment on any other things

**Comment by bheemreddy181** [comment]
But when i add my schema to the tables it wouldn't cause this issue for me

**Comment by bheemreddy181** [comment]
I think as I am Postgres 11.5 this is issues getting  triggered

**Comment by bheemreddy181** [comment]
the issue was with two instances of Postgres running at the same time once I killed the old instance this issue is resolved and we don't need a schema name
